version: "3"
services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    environment:
      SLEEP_LENGTH: 5
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 8080:8080
    depends_on:
      - "db"
    entrypoint: bash
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    ports:
      - "6000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    # volumes:
    #   - ./db:/docker-entrypoint-initdb.d/:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7000:80"
    links:
      - db:db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql

volumes:
  database: